export default {
  camera: require('./camera.png'),
  hide: require('./hide.png'),
  logo: require('./logo.png'),
  mail: require('./mail.png'),
  profile: require('./profile.png'),
  profileTab: require('./profile-tab.png'),
  homeTab: require('./home.png'),
  unionTab: require('./union.png'),
  cartTab: require('./cart.png'),
  search: require('./search.png'),
  women: require('./women.png'),
  view: require('./view.png'),
  books: require('./books.png'),
  delete: require('./delete.png'),
  plus: require('./plus.png'),
  more: require('./more.png'),
  heart: require('./heart.png'),
};
